### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by mihaic** [mihaic/graphalytics#22]

**Comment by thegeman** [comment]
Obtain Twitter dataset (http://konect.uni-koblenz.de/networks/), convert to one of the supported graph formats (edge- or vertex-based) if necessary, write configuration file.

**Comment by mihaic** [comment]
@Erackron, do you have an ETA for this?

**Comment by thegeman** [comment]
I was looking at extracting the necessary data for this graph this weekend, but I was unable to transfer the Twitter graph from the AtLarge server to DAS4 (firewall issues that I am hoping Otto can solve).

We can add a configuration file that is not "optimal"; we can select a random vertex id to start the BFS from with the risk that the BFS will reach a very small fraction of the graph. For the EVO properties we can set the maximum vertex id to some very large value.

**Comment by mihaic** [comment]
Downloading to /var/scratch/mcapota. ETA 45 min.

**Comment by mihaic** [comment]
Closed by PR #60.
