### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by thegeman** [mihaic/graphalytics#29]
E.g., Jenkins @ TUDelft. At least compilation + unit tests, perhaps integration tests.

**Comment by mihaic** [comment]
Compilation done. I also added an icon to the readme. Working on pull request testing...

**Comment by mihaic** [comment]
I also added SonarQube analysis. Only for Java code for the moment. If you have experience with SonarQube, please try to extend the analysis to Python, HTML, etc.

**Comment by mihaic** [comment]
You probably noticed that pull request testing also works. The only thing that remains to be done to close this issue is extending the SonarQube analysis to languages other than Java.

**Comment by mihaic** [comment]
Closing this. Opening issue #32 for SonarQube analysis of non-Java code.
